on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: 'shellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
